### ISSUE TITLE
Demo doesn't work

### ISSUE THREAD

**Issue by ocharles** [KtorZ/elm-notification#1]
The link to the demo is a 404.

**Comment by KtorZ** [comment]
Hey! How did you find that repo :no_mouth: ?! 

I apologize but this is for long unmaintained and examples are running using elm 0.16 which I don't recommend to look at or use; Elm has gone through a great deal of changes. 

I'll now archive this repository to make no confusion! As a replacement, I suggest to look into:

https://package.elm-lang.org/packages/pablen/toasty/latest/

with the corresponding demo:

http://pablen-toasty-demo.surge.sh/

Cheers!
